/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.infinite_labs.diceshaker.ad;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int addDieButton=0x7f050000;
        public static final int diceFacesSpinner=0x7f050002;
        public static final int diceNumberField=0x7f050001;
        public static final int dicePickerButton=0x7f05000b;
        public static final int dismissDicePickerAndRollButton=0x7f050005;
        public static final int dismissDicePickerButton=0x7f050004;
        public static final int historyList=0x7f050006;
        public static final int promptLabel=0x7f050007;
        public static final int removeDieButton=0x7f050003;
        public static final int rollButton=0x7f05000a;
        public static final int rollResultsLabel=0x7f050009;
        public static final int rollTotalLabel=0x7f050008;
    }
    public static final class layout {
        public static final int dice_picker=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int shake_or_touch_roll_to_roll=0x7f040001;
        public static final int touch_roll_to_roll=0x7f040002;
    }
}
